### ISSUE TITLE
one problem when install mlab in windows10 and python3 version

### ISSUE THREAD

**Issue by jingslaw** [ewiger/mlab#14]
Firstly, it seems that many people meet the same error code when use pip install mlab:
Traceback (most recent call last):
  File "C:/Users/lenovo/AppData/Local/Temp/mlab-1.1.4/mlab-1.1.4/setup.py", line 38, in <module>
    long_description=readme(),
  File "C:/Users/lenovo/AppData/Local/Temp/mlab-1.1.4/mlab-1.1.4/setup.py", line 20, in readme
    document = docutils.core.publish_doctree(f.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 1945: illegal multibyte sequence

this problem can be solved by add 'rb' or 'encoding='utf-8'' in function open() in line 19 as:
with open(os.path.join(os.path.dirname(__file__), 'README.rst'), 'rb') as f:

then the function read() can know what is 'README.rst' 

however a new problem emerges! 

<string>:175: (WARNING/2) Literal block expected; none found.
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

As illustration about install in readme.rst in this website:
<string>:175: (WARNING/2) Literal block expected; none found.
this error seems that you should install pywin32.

OK let's use cmd:
pip install pywin32
blablabla
Successfully installed pywin32-223

Great, let's try it again!

<string>:175: (WARNING/2) Literal block expected; none found.
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

This problem still unsolved.

I'm a physics graduate student, not a  professional programmer. So I have to know what's problem in setup.py about no commands supplied. It seems that commands about setup is missing, but the details still unknown. I have read the code one line by one line. Sadly!

If you could give me some hints, i will be really appreciative!

**Comment by gourdchen** [comment]
i meet the same problem
